#!/bin/bash

if [[ $EUID == 0 ]]; then
  PACMANCMD=( pacman )
else
  PACMANCMD=( sudo pacman )
fi

# Install packages from official repositories

BASE="base base-devel"
DEV="docker git neovim nodejs"
GNOME="baobab evince file-roller gdm gnome-backgrounds gnome-boxes gnome-calculator gnome-characters gnome-clocks gnome-color-manager gnome-control-center gnome-disk-utility gnome-font-viewer gnome-getting-started-docs gnome-keyring gnome-logs gnome-menus gnome-remote-desktop gnome-screenshot gnome-session gnome-settings-daemon gnome-shell gnome-shell-extensions gnome-system-monitor gnome-terminal gnome-themes-extra gnome-user-docs gvfs gvfs-afc gvfs-goa gvfs-google gvfs-gphoto2 gvfs-mtp gvfs-nfs gvfs-smb mousetweaks mutter nautilus networkmanager rygel simple-scan sushi tracker tracker-miners xdg-user-dirs-gtk yelp"
GNOMEEXTRA="dconf-editor gnome-nettool gnome-tweaks gnome-usage"
export ALLPACKAGES="$BASE $DEV $GNOME $GNOMEEXTRA $DESKTOPAPPS"

"${PACMANCMD[@]}" -S --needed $ALLPACKAGES || echo "This script must be run as either root or a sudoer to install pacman packages!"

# Install packages from AUR
AURPACKAGES="google-chrome android-studio discord spotify unity-editor"
if [ -x /usr/bin/yay ]; then
  echo "Yay already installed!"
else
  git clone https://aur.archlinux.org/yay.git
  cd yay
  makepkg -si
  "${PACMANCMD[@]}" -U *.pkg.xz || echo "This script must be run as either root or a sudoer to install pacman packages!"
  cd ..
  rm -rf yay
fi
yay -S --needed $AURPACKAGES
