#!/bin/bash

if [[ $EUID == 0 ]]; then
  PACMANCMD=( pacman )
else
  PACMANCMD=( sudo pacman )
fi
PACMANINSTALLFLAGS="-Sq --needed --noconfirm"

# Install packages from official repositories

# "${PACMANCMD[@]}" $PACMANINSTALLFLAGS reflector
# sudo reflector -l 100 --sort rate --save /etc/pacman.d/mirrorlist

# Uncomment if broadcom wireless driver is needed
# "${PACMANCMD[@]}" $PACMANINSTALLFLAGS broadcom-wl-dkms
# sudo modprobe wl
# sudo echo "wl" >> /etc/modules-load.d/modprobe.conf

# Uncomment if on Intel processor
# "${PACMANCMD[@]}" $PACMANINSTALLFLAGS intel-ucode mesa lib32-mesa vulkan-intel
# sudo grub-mkconfig -o /boot/grub/grub.cfg
# echo "Remember to edit /etc/mkinitcpio.conf to enable KVM"

"${PACMANCMD[@]}" -Sq --noconfirm --needed $ALLPACKAGES || echo "This script must be run as either root or a sudoer to install pacman packages!"

# Activate software
sudo systemctl enable gdm.service
sudo systemctl enable NetworkManager.service
sudo systemctl start NetworkManager.service
gsettings set org.gnome.desktop.interface gtk-theme Adapta-Eta

# Install packages from AUR
AURDEV="anaconda android-studio unityhub"
AURINTERNET="google-chrome discord synology-drive"
AURENTERTAINMENT="spotify"
AUROTHERS="debtap lightdm-slick-greeter nvm powerline-fonts-git python2-neovim"
AURPACKAGES="$AURDEV $AURINTERNET $AURENTERTAINMENT $AUROTHERS"
if [ -x /usr/bin/yay ]; then
  echo "Yay already installed!"
else
  git clone https://aur.archlinux.org/yay.git
  cd yay
  makepkg -si
  "${PACMANCMD[@]}" -U *.pkg.xz || echo "This script must be run as either root or a sudoer to install pacman packages!"
  cd ..
  rm -rf yay
fi
yay -Sq --needed --noconfirm $AURPACKAGES

if ! pacman -Qqs "chat"; then
  chatname='Chat_1.0.1-40_amd64.deb'
  chaturl="https://global.download.synology.com/download/Tools/ChatClient/1.0.1-40/Ubuntu/x86_64/Chat_1.0.1-40_amd64.deb?model=DS1517&bays=5&dsm_version=6.2.2&build_number=24922"
  curl "$chaturl" > "$chatname"
  debtap "$chatname"
fi

# Activate software
sudo systemctl enable docker.service
sudo systemctl start docker.service
