#!/bin/bash


# Variables
if [[ ! "$NEOVIMDIR" ]]; then
  NEOVIMDIR=$HOME/.config/nvim
  echo "Setting NEOVIMDIR to $NEOVIMDIR"
fi
NVIMSHAREDIR="$HOME/.local/share/nvim"

LOCALVIMCONTENTS="let nvimdir = \"$NEOVIMDIR\""

TEMPCHECKHEALTHFILE=checkhealth.log

VIMPLUGTARGETFILE="$NVIMSHAREDIR/site/autoload/plug.vim"
VIMPLUGPACKAGEDIR="$NVIMSHAREDIR/plugged"

YOUCOMPLETEME=true
YCMFLAGS=("clang-completer" "cs-completer" "java-completer" "ts-completer")
YCMDIR="$VIMPLUGPACKAGEDIR/YouCompleteMe"
echo "$VIMPLUGTARGETFILE"


# dotnvim
echo ""
echo "Pulling dotnvim from github..."
if [[ ! -d "$NEOVIMDIR" ]]; then
  git clone "https://github.com/louisch/dotnvim.git" "$NEOVIMDIR"
else
  cd "$NEOVIMDIR"
  git pull
fi


# local.vim
if [[ ! -f "$NEOVIMDIR/local.vim" ]]; then
  echo ""
  echo "Creating local.vim file with contents: $LOCALVIMCONTENTS"
  echo "$LOCALVIMCONTENTS" > "$NEOVIMDIR/local.vim"
fi


# Providers check
echo ""
echo "Checking for Python provider..."
nvim -N -u NONE -n -es -c ":checkhealth" -c ":w $TEMPCHECKHEALTHFILE"
if [[ ! $(cat $TEMPCHECKHEALTHFILE | grep Py) ]]; then
  echo "Please install Python provider before proceeding"
  rm "$TEMPCHECKHEALTHFILE"
  exit -1
fi
rm "$TEMPCHECKHEALTHFILE"
echo "Python provider found! Proceeding..."

echo "Trying to Install Node provider to Neovim..."
if [[ $EUID == 0 ]]; then
  NPMCMD=( sudo npm )
else
  NPMCMD=( npm )
fi
if [[ ! $(${NPMCMD[@]} install -g neovim) ]]; then
  echo "Please install node/npm before proceeding"
  exit -1
fi


# vim-plug
if [[ ! -f "$VIMPLUGTARGETFILE" || ! -d "$VIMPLUGPACKAGEDIR" ]]; then
  echo ""
  echo "Installing vim-plug to $VIMPLUGTARGETFILE..."
  curl -fLo "$VIMPLUGTARGETFILE" --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  echo "Opening neovim to install plugins..."
  nvim +PlugInstall +qall
fi


# YouCompleteMe
if [[ -d "$YCMDIR" ]]; then
  echo ""
  echo "Installing YouCompleteMe"
  cwd=$PWD
  cd "$YCMDIR"
  ./install.py "${YCMFLAGS[@]/#/--}"
  cd "$cwd"
fi

# Final warnings
echo ""
echo "Consider using :checkhealth to find further issues"
