#!/bin/bash
if [[ ! "$NEOVIMDIR" ]]; then
  NEOVIMDIR=~/.config/nvim
  echo "Setting NEOVIMDIR to $NEOVIMDIR"
fi
YOUCOMPLETEME=true
YCMFLAGS=("clang-completer" "cs-completer" "java-completer" "ts-completer")
YCMDIR="$NEOVIMDIR/dein/repos/github.com/Valloric/YouCompleteMe"
LOCALVIMCONTENTS="let nvimdir = \"$NEOVIMDIR\""

echo ""
echo "Pulling dotnvim from github..."
if [[ ! -d "$NEOVIMDIR" ]]; then
  git clone "https://github.com/louisch/dotnvim.git" "$NEOVIMDIR"
else
  cd "$NEOVIMDIR"
  git pull
fi

if [[ ! -f "$NEOVIMDIR/local.vim" ]]; then
  echo ""
  echo "Creating local.vim file with contents: $LOCALVIMCONTENTS"
  echo "$LOCALVIMCONTENTS" > "$NEOVIMDIR/local.vim"
fi

echo ""
echo "Checking for Python provider..."
TEMPCHECKHEALTHFILE=checkhealth.log
nvim -N -u NONE -n -es -c ":checkhealth" -c ":w $TEMPCHECKHEALTHFILE"
if [[ ! $(cat $TEMPCHECKHEALTHFILE | grep Py) ]]; then
  echo "Please install Python provider before proceeding"
  rm "$TEMPCHECKHEALTHFILE"
  exit -1
fi
rm "$TEMPCHECKHEALTHFILE"
echo "Python provider found! Proceeding..."

echo "Trying to Install Node provider to Neovim..."
if [[ $EUID == 0 ]]; then
  NPMCMD=( npm )
else
  NPMCMD=( sudo npm )
fi
if [[ ! $(${NPMCMD[@]} install -g neovim) ]]; then
  echo "Please install node/npm before proceeding"
  exit -1
fi

if [[ ! -d "$NEOVIMDIR/dein" ]]; then
  echo ""
  echo "Installing dein for the first time..."
  curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
  sh ./installer.sh "$NEOVIMDIR/dein"
  rm installer.sh  # we can remove the installation script afterwards
  echo "Now open up Neovim and run ':call dein#install()'"
fi

if [[ -d "$YCMDIR" ]]; then
  cwd=$PWD
  cd "$YCMDIR"
  git submodule update --init --recursive
  ./install.py "${YCMFLAGS[@]/#/--}"
  cd "$cwd"
fi

echo "Consider using :checkhealth to find further issues"
