#!/bin/bash
if [[ ! $SHELL == *zsh* ]]; then
  chsh -s /usr/bin/zsh
fi
if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)" "" --unattended
fi

if [[ $(uname) == *"Darwin"* ]]; then
  curl -L https://iterm2.com/shell_integration/zsh -o ~/.iterm2_shell_integration.zsh
fi
